name: CI

on:
  pull_request:
  push:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    timeout-minutes: 120
    container:
      image: python:3.10-bullseye
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run test
        run: python3 -m unittest discover tests